(function() {var implementors = {};
implementors['plist'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;<a class='enum' href='http://burntsushi.net/rustdoc/byteorder/byteorder/new/enum.Error.html' title='byteorder::new::Error'>ByteorderError</a>&gt; for <a class='enum' href='plist/enum.Error.html' title='plist::Error'>Error</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;<a class='struct' href='https://doc.rust-lang.org/nightly/collections/string/struct.FromUtf8Error.html' title='collections::string::FromUtf8Error'>FromUtf8Error</a>&gt; for <a class='enum' href='plist/enum.Error.html' title='plist::Error'>Error</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;<a class='struct' href='https://doc.rust-lang.org/nightly/collections/string/struct.FromUtf16Error.html' title='collections::string::FromUtf16Error'>FromUtf16Error</a>&gt; for <a class='enum' href='plist/enum.Error.html' title='plist::Error'>Error</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;<a class='struct' href='https://lifthrasiir.github.io/rust-chrono/chrono/format/struct.ParseError.html' title='chrono::format::ParseError'>ChronoParseError</a>&gt; for <a class='enum' href='plist/enum.Error.html' title='plist::Error'>Error</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;XmlWriterError&gt; for <a class='enum' href='plist/enum.Error.html' title='plist::Error'>Error</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;<a class='enum' href='plist/enum.Error.html' title='plist::Error'>Error</a>&gt; for <a class='enum' href='plist/enum.DeserializeError.html' title='plist::DeserializeError'>DeserializeError</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;<a class='struct' href='https://doc.rust-lang.org/nightly/std/io/error/struct.Error.html' title='std::io::error::Error'>IoError</a>&gt; for <a class='enum' href='plist/enum.Error.html' title='plist::Error'>Error</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
